# hooks for pre-commit
- id: check
  name: One Sentence Per Line Check
  description: Check if each line in the given file contains only one sentence.
  entry: onesentence check
  language: python
  types: [text, markdown, rst]
  files: \.(md|rst)$

- id: fix
  name: One Sentence Per Line Fix
  description: Fix files to ensure each line contains only one sentence.
  entry: onesentence fix
  language: python
  types: [text, markdown, rst]
  files: \.(md|rst)$